### PR TITLE
Add GC logging to node-process-metrics

### PR DESCRIPTION
**Pull request by kvigen**
Holding off on heap-dump/diff for now since that's more computationally
expensive

### CODE REVIEW

**Comment by kvigen** [comment]
cc @rgarcia

**Comment by mohit** [comment]
thumbsup

**Comment by mohit** [comment]
we should figure out how often gc-stats is emitted. hopefully not oo much :P)

**Comment by kvigen** [comment]
yeah, i will check out how much it's logging right after deploying :)

**Pull request merged**
